### ISSUE TITLE
创建账号报错，无法通过

### ISSUE THREAD

**Issue by YiXiXiao** [OracleChain/PocketEOS-Android#14]
"code":3050003,"message":"assertion failure with message: overdrawn balance","data":null

**Comment by YiXiXiao** [comment]
EOS没有测试的吗？

**Comment by swapnibble** [comment]
Maybe you tried to transfer some token greater than balance. 
Check the amount. And you should check the decimal(precision).

**Comment by YiXiXiao** [comment]
> Maybe you tried to transfer some token greater than balance.
> Check the amount. And you should check the decimal(precision).

No, I want to ask if there is a test network.
When I created the account, there was a problem, because when I created the account, I needed to pay a fee to purchase resources, so I would like to ask whether I can provide the test network to create the account and run the whole system

**Comment by luojialun** [comment]
I have the same question  "body:{"code":3050003,"message":"assertion failure with message: overdrawn balance","data":null}"

**Comment by YiXiXiao** [comment]
> I have the same question "body:{"code":3050003,"message":"assertion failure with message: overdrawn balance","data":null}"

It takes some resources to create an account. The author of this project doesn't seem to provide the test environment and account. EOS is required to create a 12-bit account consisting of 1 ~ 5, a ~ z.

**Comment by lucanjp** [comment]
The current PE open source version is connected to EOS real nodes.Creating an account PE provides only paid creation for the time being.
