### ISSUE TITLE
登录不了dapp

### ISSUE THREAD

**Issue by ivalimmb** [OracleChain/PocketEOS-Android#18]
你好 在开源版本发现如下问题:
      点击开始调试 跳转到dapp页面 但dapp并没有登录成功 包括打开其他dapp ( 如 https://betdice.one ) 也没有登录成功 已经确定导入了账号 请问有解决方案吗?

**Comment by HallCheng** [comment]
+1

**Comment by lucanjp** [comment]
dapp登录需要重写scatter，目前支持scatter的版本已经在我们的开源计划中了，敬请期待~
