### ISSUE TITLE
pocketEOS build错误

### ISSUE THREAD

**Issue by a591371947** [OracleChain/PocketEOS-Android#19]
> Configure project :app
Configuration 'androidTestCompile' in project ':app' is deprecated. Use 'androidTestImplementation' instead.
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > org.gradle.api.tasks.TaskInputs.file(Ljava/lang/Object;)Lorg/gradle/api/tasks/TaskInputs;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get fu
ll insights.

* Get more help at https://help.gradle.org

**Comment by lucanjp** [comment]
rebuild！
