### ISSUE TITLE
dapp与app交互失败

### ISSUE THREAD

**Issue by wyh00544** [OracleChain/PocketEOS-Android#20]
这个版本的Dapp无法账户识别，无法做转账操作

**Comment by MrHou** [comment]
@wyh00544 你好，你有找到Dapp和账户识别的方法吗 ？我现在也是有点问题，如有方法，望回复，谢谢

**Comment by wyh00544** [comment]
没有呢，你那有别的方案吗？

**Comment by wyh00544** [comment]
我还在研究这个。有别人给你回信吗？

在 2019-03-11 20:17:45，"Haven K" <notifications@github.com> 写道：


@wyh00544 你好，你有找到Dapp和账户识别的方法吗 ？我现在也是有点问题，如有方法，望回复，谢谢

**Comment by lucanjp** [comment]
需要重写scatter.js

**Comment by MrHou** [comment]
> 我还在研究这个。有别人给你回信吗？ 在 2019-03-11 20:17:45，"Haven K" <notifications@github.com> 写道： @wyh00544 你好，你有找到Dapp和账户识别的方法吗 ？我现在也是有点问题，如有方法，望回复，谢谢 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

Hello  有解决问题吗 ？notifications@github.com这个是你的email吗 ？

**Comment by lucanjp** [comment]
请借鉴参考另外一个项目pe-js-sdk    https://github.com/OracleChain/pe-js-sdk
