### ISSUE TITLE
关于转账问题

### ISSUE THREAD

**Issue by luoxiaohui** [OracleChain/PocketEOS-Android#6]

**Comment by lucanjp** [comment]
我们的服务器只是做了转发，其实是直接连接的节点，并且网络请求里面也没有携带私钥，交易发起者签名所需要的私钥是在本地的，并且签名过程也是在本地完成的。




| |
卢金鹏
邮箱：lujinpeng_mail@163.com
|

签名由 网易邮箱大师 定制

在2018年06月28日 14:54，luoxiaohui 写道：

再次请教下大佬，转账操作我看到你们代码是需要经过服务器的，那岂不是需要将私钥带过去，这样是不是不安全，或者不合理？
