### ISSUE TITLE
License message removed. ( EOS Commander source by PLACTAL.IO )

### ISSUE THREAD

**Issue by swapnibble** [OracleChain/PocketEOS-Android#8]
Hi, I'm Eric(@swapnibble) from plactal.io .

This project uses source of [EOSCommander](https://github.com/plactal/EosCommander) for interfacing EOSIO blockchain. 

But the readme of PocketEOS says "using only ECDSA" part. And almost sources under blockchain package are sources of EOS Commander. ( the original license message replaced with "Created by pocketEos".  Transaction.java include todo comment in Korean.).

As the author of EOS Commander, I want to restore the license message.
I believe it happened by mistake.

**Comment by songgeng87** [comment]
i'm so sorry to mistake you.
we will check that, and restore your license message.
thanks for your eoscommander again.

**Comment by issaxyz** [comment]
@swapnibble Seems like the license messages were missing when our colleague import the EOScommander utility, and the IDEA automatically cover it with the wrong license.

**Comment by issaxyz** [comment]
We've fixed the issue~
And thx again for you team as a vanguard model in EOS open-source projects.
We'll make it better and stronger~😄

**Comment by swapnibble** [comment]
Thanks a lot for rapid fix.
I'll cast my vote for OracleChain as BP. :)
